on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: "Testing Git Action"
        run: pwd

      - name: "Testing printing"
        run: echo Mostafa
